title: "Ravelry: Hot Right Now"
author: "by Alex McSween"
format: 
  dashboard:
    nav-buttons: 
     - icon: github
       href: https://github.com/alexmcsw/ravelry-table
    theme:
      - brand
      - custom.scss
    scrolling: true 
    expandable: false

project:
  output-dir: docs
execute:
  freeze: auto

