title: "Ravelry: Hot Right Now"
author: "by Alex McSween"
format: 
  dashboard:
    nav-buttons: 
     - icon: github
       href: https://github.com/alexmcsw/ravelry-table
     - icon: activity
       href: https://www.ravelry.com/people/amcsw
    theme:
      - brand
      - custom.scss
project:
  output-dir: docs
execute:
  freeze: auto